server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: userApp
          uri: http://localhost:8082
          predicates:
            - Path=, 
        - id: point
          uri: http://localhost:8083
          predicates:
            - Path=/points/**, 
        - id: agreement
          uri: http://localhost:8084
          predicates:
            - Path=/agreements/**, 
        - id: benefits
          uri: http://localhost:8085
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: userApp
          uri: http://userApp:8080
          predicates:
            - Path=, 
        - id: point
          uri: http://point:8080
          predicates:
            - Path=/points/**, 
        - id: agreement
          uri: http://agreement:8080
          predicates:
            - Path=/agreements/**, 
        - id: benefits
          uri: http://benefits:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
